language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpspec run --config=phpspec.yml --no-interaction